# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21f0725d0a349db427d8fbbccf727e3ac0414d248f389cf008240a6c0de238554f0026e455551f1f69b3064a43c936cc19fd434850528bbb6dfb38f3f84c1d21

test:
  secret_key_base: a7fa9acac984b04c0e85abe2c632b13ab99088c486f8621c5adcac04fddd62e32d54739be6c6788ca7e660a59f33507b924b2613cc0f20bf28cc3d6cc4a96c40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
